import { useEffect, useState } from "react";
import { api } from "./api.js";
import { GapInterview } from "./GapInterview.jsx";

const PRIORITY_ORDER = { high: 0, medium: 1, low: 2 };

const TITLES = { questions: "Questionnaire.", interview: "Interview.", findings: "Findings." };

export function GapQuestions({ client, onBack }) {
  const [tab, setTab] = useState("questions");
  // Bumped after an evaluation completes so the findings tab refetches instead of
  // showing the stale "no assessment yet" state it cached on first mount.
  const [findingsVersion, setFindingsVersion] = useState(0);

  return <section className="flow">
    <p className="eyebrow">Gap assessment · {client.organization.name}</p>
    <h2>{TITLES[tab]}</h2>
    <div className="agent-buttons">
      {["questions", "interview", "findings"].map((name) => (
        <button key={name} className={tab === name ? "" : "outline"} onClick={() => setTab(name)}>
          {name === "questions" ? "Questionnaire" : name === "interview" ? "Interview" : "Findings"}
        </button>
      ))}
    </div>
    {tab === "questions" && <Questionnaire client={client}/>}
    {tab === "interview" && <GapInterview client={client} onComplete={() => { setFindingsVersion((n) => n + 1); setTab("findings"); }}/>}
    {tab === "findings" && <Findings client={client} version={findingsVersion}/>}
    <button className="secondary" onClick={onBack}>Back</button>
  </section>;
}

/** Long-running: the questionnaire is generated by one LLM call per control batch.
 *  Cold generation is measured at ~60s, so the wait is explained rather than hidden. */
function Questionnaire({ client }) {
  const [questions, setQuestions] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    let live = true;
    api.gapQuestions(client.client_id)
      .then((result) => live && setQuestions(result))
      .catch((err) => live && setError(err.message));
    return () => { live = false; };
  }, [client.client_id]);

  if (error) return <p className="error">{error}</p>;
  if (!questions) return <Preparing
    title="Preparing your assessment…"
    lede="We're reviewing the controls that apply to your organisation and writing the interview questions. This usually takes about a minute — you can leave this page and come back."
  />;

  const groups = groupBy(questions, (question) => question.is_universal ? null : question.domain);

  return <>
    <p className="hint">{questions.length} questions, grouped by control domain.</p>
    {groups.map(([domain, items]) => (
      <div className="workspace" key={domain ?? "universal"}>
        <p className="eyebrow">{domain ?? "Asked of every client"}</p>
        <div className="client-list">
          {items.map((question) => (
            <div className="client-card" key={question.question_id}>
              <strong>{question.text}</strong>
              {question.control_ids.length > 0 && <span>{question.control_ids.join(", ")}</span>}
            </div>
          ))}
        </div>
      </div>
    ))}
  </>;
}

function Findings({ client, version }) {
  const [findings, setFindings] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    let live = true;
    api.gapFindings(client.client_id)
      .then((result) => live && setFindings(result))
      .catch((err) => live && setError(err.message));
    return () => { live = false; };
  }, [client.client_id, version]);

  if (error) return <p className="hint">{error}</p>;
  if (!findings) return <Preparing
    title="Assessing your answers…"
    lede="Each answer is being reviewed against the controls it covers to work out what's already in place and what needs attention."
  />;

  const open = findings.filter((finding) => finding.status === "open");
  const sorted = [...findings].sort((a, b) =>
    (PRIORITY_ORDER[a.priority] - PRIORITY_ORDER[b.priority]) ||
    (a.status === b.status ? 0 : a.status === "open" ? -1 : 1));

  return <>
    <p className="hint">
      {open.length} open {open.length === 1 ? "gap" : "gaps"} of {findings.length} areas assessed
      {" · "}{count(findings, "high")} high, {count(findings, "medium")} medium, {count(findings, "low")} low priority.
    </p>
    <div className="client-list">
      {sorted.map((finding) => (
        <div className="finding-card" key={finding.finding_id}>
          <div className="finding-tags">
            <span className={`tag tag-${finding.priority}`}>{finding.priority} priority</span>
            <span className={`tag tag-${finding.status}`}>{finding.status}</span>
            {finding.control_ids.length > 0 && <span className="tag tag-control">{finding.control_ids.join(", ")}</span>}
          </div>
          <strong>{finding.summary}</strong>
          <p className="finding-question">{finding.question_text}</p>
          <p className="finding-advice">{finding.suggestion}</p>
        </div>
      ))}
    </div>
  </>;
}

function Preparing({ title, lede }) {
  return <div className="workspace preparing">
    <div className="spinner" aria-hidden="true"/>
    <strong>{title}</strong>
    <p className="hint">{lede}</p>
  </div>;
}

function count(findings, priority) {
  return findings.filter((finding) => finding.priority === priority).length;
}

function groupBy(items, keyOf) {
  const order = [];
  const buckets = new Map();
  for (const item of items) {
    const key = keyOf(item);
    if (!buckets.has(key)) { buckets.set(key, []); order.push(key); }
    buckets.get(key).push(item);
  }
  return order.map((key) => [key, buckets.get(key)]);
}
